project:
  type: website

website:
  title: "water_boil_notices-mariaprobert"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - 01-cleaning.qmd
      - 02-analysis.qmd
      

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



